'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, CheckCircle2, LockKeyhole } from 'lucide-react'

export default function FundPage() {
  const [funded, setFunded] = useState(false)
  return <main className="arena-grid min-h-screen px-5 py-6 sm:px-8"><header className="mx-auto max-w-5xl"><Link href="/sponsor" className="inline-flex items-center gap-2 text-sm text-white/55 hover:text-white"><ArrowLeft size={15} /> For sponsors</Link></header><section className="mx-auto max-w-2xl py-16"><p className="text-xs font-semibold uppercase tracking-[.25em] text-cyan-200/70">Sponsor flow</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">Create a developer bounty.</h1><p className="mt-5 text-base leading-7 text-white/60">Define the problem, set the reward, and lock the opportunity for the next gladiator. This form is currently in mock mode.</p>{funded ? <div className="liquid-glass mt-10 rounded-[1.75rem] p-7"><CheckCircle2 className="text-emerald-200" size={26} /><h2 className="mt-5 text-2xl font-semibold">Challenge funded in demo mode.</h2><p className="mt-3 text-sm leading-6 text-white/55">No USDT transfer was submitted. Your next step is to connect the escrow adapter and wallet approval flow.</p><Link href="/lobby" className="mt-7 inline-flex min-h-11 items-center rounded-full bg-white px-5 text-sm font-semibold text-black">View lobby</Link></div> : <form className="liquid-glass mt-10 space-y-5 rounded-[1.75rem] p-6" onSubmit={(event) => { event.preventDefault(); setFunded(true) }}><label className="block text-sm font-medium">Select challenge<input className="mt-2 min-h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4 text-white outline-none" placeholder="e.g. Two Sum, Reverse Linked List" required /></label><label className="block text-sm font-medium">Bounty amount (USDT)<input className="mt-2 min-h-12 w-full rounded-2xl border border-white/10 bg-black/20 px-4 text-white outline-none" type="number" min="1" placeholder="150" required /></label><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-white text-sm font-semibold text-black" type="submit"><LockKeyhole size={16} /> Lock funds in escrow</button><p className="text-center text-xs leading-5 text-white/35">Mock mode — no Nimiq Pay popup or transfer will be triggered.</p></form>}</section></main>
}
